(library
 (name hamlet_subtractor_cross_cu_fixture)
 (package hamlet-subtractor)
 (wrapped false)
 (modules hamlet_subtractor_cross_cu_fixture)
 (libraries hamlet)
 (preprocess
  (pps ppx_hamlet)))

(library
 (name hamlet_subtractor_integration_fixture)
 (wrapped false)
 (modules hamlet_subtractor_integration_fixture)
 (libraries hamlet hamlet_subtractor_cross_cu_fixture)
 (preprocessor_deps
  (package hamlet-subtractor))
 (preprocess
  (staged_pps hamlet-subtractor.ppx)))

(library
 (name hamlet_subtractor_generic_definition_fixture)
 (wrapped false)
 (modules hamlet_subtractor_generic_definition_fixture)
 (libraries hamlet)
 (preprocessor_deps
  (package hamlet-subtractor))
 (preprocess
  (staged_pps hamlet-subtractor.ppx)))

(library
 (name hamlet_subtractor_layer_fixture)
 (wrapped false)
 (modules hamlet_subtractor_layer_fixture)
 (libraries hamlet hamlet_subtractor_cross_cu_fixture)
 (preprocessor_deps
  (package hamlet-subtractor))
 (preprocess
  (staged_pps hamlet-subtractor.ppx)))

(test
 (name hamlet_subtractor_layer_runtime_test)
 (modules hamlet_subtractor_layer_runtime_test)
 (libraries hamlet hamlet_subtractor_layer_fixture))

(library
 (name hamlet_subtractor_nested_inner_fixture)
 (wrapped false)
 (modules hamlet_subtractor_nested_inner_fixture)
 (libraries hamlet)
 (preprocessor_deps
  (package hamlet-subtractor))
 (preprocess
  (staged_pps hamlet-subtractor.ppx)))

(library
 (name hamlet_subtractor_nested_outer_fixture)
 (wrapped false)
 (modules hamlet_subtractor_nested_outer_fixture)
 (libraries hamlet hamlet_subtractor_nested_inner_fixture)
 (preprocessor_deps
  (package hamlet-subtractor))
 (preprocess
  (staged_pps hamlet-subtractor.ppx)))

(library
 (name hamlet_subtractor_generic_helper_producer)
 (wrapped false)
 (modules hamlet_subtractor_generic_helper_producer)
 (libraries hamlet)
 (preprocessor_deps
  (package hamlet-subtractor))
 (preprocess
  (staged_pps hamlet-subtractor.ppx)))

(library
 (name hamlet_subtractor_generic_helper_consumer)
 (wrapped false)
 (modules hamlet_subtractor_generic_helper_consumer)
 (libraries hamlet hamlet_subtractor_generic_helper_producer)
 (preprocessor_deps
  (package hamlet-subtractor))
 (preprocess
  (staged_pps hamlet-subtractor.ppx)))

(alias
 (name runtest)
 (deps
  hamlet_subtractor_generic_definition_fixture.cma
  hamlet_subtractor_layer_fixture.cma
  hamlet_subtractor_generic_helper_consumer.cma
  hamlet_subtractor_nested_outer_fixture.cma
  hamlet_subtractor_integration_fixture.cma))

(rule
 (alias runtest)
 (deps
  (sandbox none)
  installed_consumer.sh)
 (action
  (setenv
   HAMLET_SUBTRACTOR_DUNE_ACTION
   1
   (run %{dep:installed_consumer.sh}))))

(executable
 (name hamlet_subtractor_fast_driver)
 (modules hamlet_subtractor_fast_driver)
 (libraries hamlet_subtractor_ppx ppxlib))

(cram
 (package hamlet-subtractor)
 (deps ./hamlet_subtractor_fast_driver.exe))
