(* Fixture: a PPX-generated [<Mod>.Tag.provide] call. The Tag.provide flavour
   is never stale by construction — the handler is a one-arm pure [give]
   generated by the PPX — so the walker recognises the path and emits
   nothing. This fixture verifies that the recognition is clean: no stderr
   diagnostic, no false finding, exit 0.

   The fixture additionally contains a genuine stale [Combinators.provide]
   so that the e2e test has something concrete to assert against — the
   analyzer should still report the [Combinators.provide] row but stay
   silent about the [Tag.provide] row. *)

open Hamlet.Combinators

[%%hamlet
module type Svc = sig
  type svc_error = [ `Svc_error of string ]
  val call : unit -> (unit, [> svc_error ], 'r) t
end]

let prog () : (unit, _, _) Hamlet.t =
  let* (module S : Svc.S) = Svc.Tag.summon () in
  S.call ()

let clean_run () =
  prog ()
  |> Svc.Tag.provide
       (module struct
         let call () = success ()
       end)
